apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hogehoge-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/u1roh/k8s-sandbox.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
