apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: whalesay
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: hoge
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
